owners:
  - nealef
autoMerge: false
commandNotFound: This command is not found, to see list of commands you can use, please type **/ompBot help**. Thanks.
buildPassMessage: 'Build Passed :tada:. Comment **/ompBot merge** to merge the PR if you have correct access rights. If not then you can ask one of maintainers for the review. To see list of all reviewers use **/ompBot reviewList**.'
mergeMessage: 'Thanks you for your contribution :v:. Happy contributing :fire:' 
errorMessage: Build failed. Please check the errors and fix it. Thanks.
prOpenMessage: 'Thanks you for opening this PR :v:. Please wait for tests to run. To know more about me just type **/ompBot help** :smile:.' 
