#
# Derived from the Dockerfiles for RedCoolBeans Project
#
FROM clefos:latest

MAINTAINER 	The ClefOS Project <neale@sinenomine.net>

LABEL 		com.baculasystems.bacula.version="5.2.13" 

VOLUME 		/var/lib/postgresql/data
