node('suse') {
    def app
    def app2
    def app3
    def app4
    def app5
    def app6
    def app7
    def app8
    def app9
    def app10
    def app11
    stage('Clone repository') {
        checkout scm
    }
    stage('Build image') {
        DOCKER_HOME = tool "docker"
        dir("suse"){
        sh "cd base && sudo ./config.sh && cd .."
        sh "mv base/Dockerfile ."
        sh "mv base/sles-15-docker.tar.xz ."
        app3 = docker.build("vedarth/sles")
        sh "mv Dockerfile base/"
        sh "mv sles-15-docker.tar.xz base/"
        sh "mv django/Dockerfile ."
        app = docker.build("vedarth/django")
        sh "mv Dockerfile django/"
        sh "mv redis/Dockerfile ."
        app2 = docker.build("vedarth/redis")
        sh "mv Dockerfile redis/"
        sh "mv golang/Dockerfile ."
        sh "mv golang/go-wrapper ."
        app4 = docker.build("vedarth/golang")
        sh "mv Dockerfile golang/"
        sh "mv go-wrapper golang/"
        sh "mv jupyter/Dockerfile ."
        app5 = docker.build("vedarth/jupyter")
        sh "mv Dockerfile jupyter/"
        sh "mv mariadb/allow-skip-name.cnf ."
        sh "mv mariadb/docker-entrypoint.sh ."
        sh "mv mariadb/Dockerfile ."
        sh "mv mariadb/fix-permissions.sh ."
        app6 = docker.build("vedarth/mariadb")
        sh "mv allow-skip-name.cnf mariadb/"
        sh "mv docker-entrypoint.sh mariadb/"
        sh "mv Dockerfile mariadb/"
        sh "mv fix-permissions.sh mariadb/"
        sh "mv nginx/Dockerfile ."
        app7 = docker.build("vedarth/nginx")
        sh "mv Dockerfile nginx/"
        sh "mv nodejs/Dockerfile ."
        app8 = docker.build("vedarth/nodejs")
        sh "mv Dockerfile nodejs/"
        sh "mv postgresql/Dockerfile ."
        sh "mv postgresql/postgresql-setup ."
        sh "mv postgresql/postgresql.conf ."
        sh "mv postgresql/start_postgres.sh ."
        sh "mv postgresql/supervisord.conf ."
        app9 = docker.build("vedarth/postgresql")
        sh "mv Dockerfile postgresql/"
        sh "mv postgresql-setup postgresql/"
        sh "mv postgresql.conf postgresql/"
        sh "mv start_postgres.sh postgresql/"
        sh "mv supervisord.conf postgresql/"
        sh "mv wordpress/scripts ."
        sh "mv wordpress/Dockerfile ."
        app10 = docker.build("vedarth/wordpress")
        sh "mv Dockerfile wordpress/"
        sh "mv scripts wordpress/"
        }
    }
}